# Generated by Django 4.2.4 on 2023-11-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_incorporacion', models.DateField()),
                ('año_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estado', models.CharField(choices=[('Vigente', 'Vigente'), ('Suspendido', 'Suspendido'), ('Retirado', 'Retirado')], max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
